Update beta.yml

diff --git a/.github/workflows/beta.yml b/.github/workflows/beta.yml
--- a/.github/workflows/beta.yml
+++ b/.github/workflows/beta.yml
@@ -93,3 +93,18 @@ jobs:
           for file in `ls ${{ github.workspace }}/app/build/outputs/mapping/*/missing_rules.txt`; do
             mv "$file" ${{ github.workspace }}/mapping/missing_rules.txt
           done
+
+      - name: Check Build production
+        run: |
+          cd ${{ github.workspace }}/apk/
+          if [ ! -e legado_*.apk ]; then
+            echo "Build production not found! Check gradle logs."
+            exit 1
+          fi
+
+      - name: Upload App To Artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: legado.${{ env.product }}.${{ env.type }}
+          if-no-files-found: ignore
+          path: ${{ github.workspace }}/apk/*.apk
